### ISSUE TITLE
ImportError : no module named djcelery.backends.cache when trying to create badge

### ISSUE THREAD

**Issue by 6tine** [concentricsky/badgr-server#126]
## System information & context:
- Operating system you are using: Ubuntu 12.04
- Browser & version: Firefox version 52.0.2

I've installed badgr-ui and badgr-server thanks to the readme.txt.

## Description of issue or feature request, including any error messages:

However, I have a problem when i'm trying to create a badge from badgr-ui, there is this error message : 

"ImportError : no module named djcelery.backends.cache"

![image](https://user-images.githubusercontent.com/34345329/57627091-8e55a600-7597-11e9-9d5a-887f624e905c.png)

![image](https://user-images.githubusercontent.com/34345329/57626967-4afb3780-7597-11e9-890e-5c7c87dc981f.png)

In fact, I can see the badge associated to the issuer on my user account, but when i restart the server, all the badges i've tried to create before, disappear... The badge are not saved in the server.

I've search how to resolve it but i don't find anything. Do you know how to resolve this problem of djcelery please ?

Here the complete error message : 
[no_module_djcelery-backends-cache.txt](https://github.com/concentricsky/badgr-server/files/3173272/no_module_djcelery-backends-cache.txt)

**Comment by boona11** [comment]
Just go to settins_local.py and change this line:

`CELERY_RESULT_BACKEND = 'djcelery.backends.cache:CacheBackend'`
to
`CELERY_RESULT_BACKEND = 'django-db'`

I spent one night on this error :)

**Comment by 6tine** [comment]
Ok thanks a lot ! I've tried with CELERY_RESULT_BACKEND = 'amqp://localhost:5672/' too and it works !

But I'm going to use your solution, thanks again :)

**Comment by boona11** [comment]
You are welcome bro 
Right now I am trying to customize the api to add pathways to the badgr, I hope they open the pathways code to be open source soon.

**Comment by ottonomy** [comment]
@boona11 we are not planning to release the source code for pathways.badgr.io -- that is a closed source project. However we are open to collaboration around the ideas of Open Pathways and standards development around how to represent pathways in common ways across products.

@6tine you can set `CELERY_RESULT_BACKEND = None` and if you like `CELERY_ALWAYS_EAGER = True` to use the system without asynchronous task processing. Asynchronous processing is not necessary, and doesn't really get substantially used in badgr-server. We at Concentric Sky choose to run a fairly large background processing system in Badgr for the few things that it provides, as well as looking forward to future potential capabilities that lean heavily on background/async processing.

Can you confirm which commit/tag/branch you have checked out of badgr-server where you encountered this issue? This should be resolved and not a barrier to new installers.

**Comment by 6tine** [comment]
Thanks for the help !
I was working with the branch : develop

**Comment by ottonomy** [comment]
@6tine I've updated the `settings_local.example.py` in 296799c5 which will be on develop before too long.

**Comment by 6tine** [comment]
Ok thank you !
