### ISSUE TITLE
Problem with CSS when trying to deploy badgr-server and badgr-ui

### ISSUE THREAD

**Issue by 6tine** [concentricsky/badgr-server#130]
## System information & context:
- Operating system you are using: Ubuntu 12.04
- Browser & version: Firefox 52.0.2

## Description of issue or feature request, including any error messages:

Hi !

I'm trying to deploy badgr-server and badgr-ui on my local network. (The IP of the machine where is running badgr-server and badgr-ui is 192.168.1.75).  I've applied modifications on settings_local.py for badgr-server and in package.json for badgr-ui in order ton run the server on 192.168.1.75:8000 and 192.168.1.75:4200 (I don't know if I can do that, i'm probably using the wrong way to do this ?)

![image](https://user-images.githubusercontent.com/34345329/58031623-0e908400-7b21-11e9-9fef-893e9aba4a0e.png) 
(settings_local.py)

![image](https://user-images.githubusercontent.com/34345329/58031701-3849ab00-7b21-11e9-811c-16083fd91890.png) 
(package.json)

I can use badgr-ui (create account, create issuer, awars badges etc.), but I have some problems with CSS, especially with badgr-server, and a little with badgr-ui. In fact, there is "localhost" in some parts of the css code, that's why css isn't found. What do I have to do please ?

![image](https://user-images.githubusercontent.com/34345329/58031309-6e3a5f80-7b20-11e9-8b1e-572682b394d7.png)
(badgr-server, css isn't found)

![image](https://user-images.githubusercontent.com/34345329/58031402-a2ae1b80-7b20-11e9-9ce4-522e42aa90d3.png)
(badgr-ui)

---
Notes (safe to delete):

- You can also [add a screenshot](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) or [add a file](https://github.com/blog/2061-attach-files-to-comments)
- When reporting a feature request, consider writing one or more [user stories](https://www.mountaingoatsoftware.com/agile/user-stories)

**Comment by boona11** [comment]
Did you try run the server on the local host? is it working properly?
What is the value of this variable in the local_setting.py
ALLOWED_HOSTS

**Comment by boona11** [comment]
show me the sttings_local.py and settings .py files

**Comment by 6tine** [comment]
Yes when i was running in localhost it was working properly
I have ALLOWED_HOSTS = ['*']

Well i've forgotten to change http_origin = "http://localhost:8000" to http_origin = "http://192.168.1.75:8000" in my settings.py file ! Thank you for reminding me of this file haha
Now CSS is working for badgr-server !

However I still have a little problem here with badgr-ui (may be i've forgotten some configurations?): 

"localhost does not allow the connection"

![image](https://user-images.githubusercontent.com/34345329/58076921-b5216700-7bab-11e9-8f49-c3071da93897.png)

If you still want to see the files, here they are : 

[settings.txt](https://github.com/concentricsky/badgr-server/files/3201292/settings.txt)

[settings_local.txt](https://github.com/concentricsky/badgr-server/files/3201293/settings_local.txt)

Thank you !

**Comment by 6tine** [comment]
Finally I've made some additionnal configurations in badg-server website (i've change urls for the badgr app from localhost to 192.168.1.75) and it's working now !
