### ISSUE TITLE
ImportError: No module named client_admin

### ISSUE THREAD

**Issue by ajindra** [concentricsky/badgr-server#16]
I'm trying to get the current github version installed on an Ubuntu LTS 14.04 Trusty Tahr and constantly run into  "ImportError: No module named client_admin" when I call one of the manage.py commands.
What's my fault? - Thx.

**Comment by ajindra** [comment]
After manually installing several packages which should have been installed by the "pip install -r requirements.txt" command I got somewhat further but now am stuck at
File "/.../badgr-home/env/local/lib/python2.7/site-packages/jingo/__init__.py", line 12, in <module>
    from django.template.context import get_standard_processors
ImportError: cannot import name get_standard_processors

**Comment by ottonomy** [comment]
Interesting error, @ajindra. To be clear, you resolved the original issue that pip did not manage to install client_admin automatically, right?

Could you post the output of `pip freeze` so that we can see what version of the required modules you are using? 

Does this error go away if you change to `Debug = False` in apps/mainsite/settings_local.py?

**Comment by ajindra** [comment]
(env) .../code# pip freeze
Django==1.8.3
Django-Select2==4.2.2
Jinja2==2.8
MarkupSafe==0.23
Pillow==2.9.0
PyLD==0.6.8
PyYAML==3.11
argparse==1.2.1
boto==2.38.0
cookies==2.2.1
distribute==0.7.3
django-allauth==0.23.0
django-autoslug==1.8.0
django-basic-models==2.1.0
django-boto==0.3.9
django-cachemodel==2.0.0
django-client-admin==1.1.1
django-debug-toolbar==1.3.2
django-rest-swagger==0.3.3
django-reversion==1.9.1
django-ses==0.7.0
django-sky-ckeditor==0.9.8
django-storages==1.1.8
djangorestframework==3.1.3
jingo==0.7.1
jsonfield==1.0.3
jsonschema==2.5.1
mock==1.3.0
netaddr==0.7.15
oauthlib==1.0.1
pbr==1.4.0
pypng==0.0.18
python-dateutil==2.4.2
python-memcached==1.57
python-openid==2.2.5
pytz==2015.4
requests==2.7.0
requests-oauthlib==0.5.0
responses==0.4.0
rfc3987==1.3.4
rules==0.4
simplejson==3.8.0
six==1.9.0
sqlparse==0.1.16
wsgiref==0.1.2

The error persists if I deactivate debugging.

**Comment by ajindra** [comment]
The original error concerning the missing client_admin was resolved. I had some more, deactivated the "MySQL-python" requirement because it complained about not being configured correctly and stopped the pip install. I had to update the "distribute" package because mock complained about outdated setuptools and then the pip install command completed fine:
Installing pbr script to /.../env/bin
Successfully installed Pillow boto django-boto django-ses django-storages python-memcached django-rest-swagger responses rules django-debug-toolbar django-autoslug six sqlparse netaddr jsonschema simplejson PyLD rfc3987 jsonfield django-cachemodel django-basic-models django-sky-ckeditor django-client-admin python-dateutil PyYAML cookies mock pbr
Cleaning up...
The npm install had two warnings as well:
npm WARN package.json BadgeTrust@0.0.2 No repository field.
npm WARN package.json events@1.0.2 events is also the name of a node core module.

**Comment by ottonomy** [comment]
The versions of Django, Jinja2 and jingo that you've got in your environment are quite a bit different from the ones required in requirements.txt -- this is causing a mismatch as the packages try to work together.

We haven't updated Badgr to Django 1.8 yet, though this is the sort of little issue that can arise when we dig into that process. We'd love some folks experimenting with changing these packages, but probably want to do it only a couple packages at a time to make sure that the number of little mismatches like this is manageable.

Are you using a virtualenv? https://virtualenv.pypa.io/en/latest/

**Comment by ajindra** [comment]
Arrghh, my fault - I removed all version information from requirements.txt at some point earlier in the process :-/ Thanks for your help (and yes, I am using virtualenv).
