### ISSUE TITLE
500 Internal Server Error on Issue Assertion

### ISSUE THREAD

**Issue by benzaked** [concentricsky/badgr-server#163]
## System information & context:
- Operating system : Ubuntu 18.04
- Browser & version: chrome
I got this error when I tried to issue a badge using postman(localhost with badgr-server and badgr-ui): 
'Settings' object has no attribute 'UNSUBSCRIBE_SECRET_KEY'
Request URL: http://localhost:8000/v2/badgeclasses/voFc6ZTHSrS1hs3QjyUuzw/assertions
Django Version: 1.11.20
Python Version: 2.7.15

I can see the badge in the user's backpack but there is an error during API request.
Thanks!

**Comment by nqthqn** [comment]
Add `UNSUBSCRIBE_SECRET_KEY = "somesecret"` to your settings
