### ISSUE TITLE
publickey issues

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#17]
This might be because I am a total github noobie, but the instructions to install badgr always give me publickey problems. For instance:
```$ git clone git@github.com:concentricsky/badgr-home.git code
Cloning into 'code'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I can install it just fine if I use https, but then later when I try to pip install, I get the same error:
```Downloading/unpacking git+ssh://git@stash.concentricsky.com/bp/badgecheck.git@v0.2.5 (from -r requirements.txt (line 65))
  Cloning ssh://git@stash.concentricsky.com/bp/badgecheck.git (to v0.2.5) to /tmp/pip-3kNGrA-build
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

How do I get around this?

**Comment by sacrophyte** [comment]
lol, my markdown formatting leaves something to be desired as well..... *sigh*

**Comment by sacrophyte** [comment]
Reading a github help page now:

https://help.github.com/articles/error-permission-denied-publickey/

**Comment by sacrophyte** [comment]
I have successfully added a SSH key for my account on github. However, based on the last error message (pip install), do I also need a ssh key for git@stash.concentricsky.com?

**Comment by ottonomy** [comment]
Closed by https://github.com/concentricsky/badgr-server/commit/bec8c948fbe4491941f44738f1f99b88c197d9ca
