### ISSUE TITLE
_cffi_backend.so: undefined symbol: PyUnicodeUCS2_FromUnicode

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#19]
Why is a personal copy of python installed in my environment? Why not use the system-wide version of python? I wonder if this is leading to the undefined symbol in some way.

When running pip install, I get an error:
      File "/home/cschultz/badgr/env/local/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
        import _cffi_backend as backend
    ImportError: /home/cschultz/badgr/env/local/lib/python2.7/site-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS2_FromUnicode
    Complete output from command /home/cschultz/badgr/env/bin/python -c "import setuptools, tokenize;__file__='/home/cschultz/badgr/env/build/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OH_hmx-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/cschultz/badgr/env/include/site/python2.7:

**Comment by sacrophyte** [comment]
Log files:
[pip_install.txt](https://github.com/concentricsky/badgr-server/files/52867/pip_install.txt)
[pip_debug_log.txt](https://github.com/concentricsky/badgr-server/files/52868/pip_debug_log.txt)

**Comment by sacrophyte** [comment]
Had a long email thread with Nate; in the end, if I install all the following packages, pip install works:

["git", "git-core", "python-virtualenv", "gcc", "python-pip", "python-devel", "libjpeg-turbo", "libjpeg-turbo-devel", "zlib-devel", "mariadb-devel", "openldap-devel", "cyrus-sasl-devel", "swig", "libxslt-devel", "automake", "autoconf", "libtool", "libffi-devel"]

I am not sure what the minimum number of packages are. Also, keep in mind this is in addition to the other prerequisites already listed in the readme.md.

**Comment by ottonomy** [comment]
Thanks, @sacrophyte. The list posted above is a set of prerequisites to install and run this application on a bare ubuntu machine. The list may vary depending on operating system. The instructions included in our Readme should be sufficient for OS X installs.

Closed by 3e6ece8

**Comment by ZephyrYin** [comment]
recompile your python with ./configure --prefix=/usr --enable-unicode=ucs4
