### ISSUE TITLE
badgecheck

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#20]
This is a new issue spun out of "publickey issues #17".

The following line appears in requirements.txt:
git+ssh://git@stash.concentricsky.com/bp/badgecheck.git@v0.2.5

However, I don't believe the public has access to that. On Nate's advice, I commented that out of requirements.txt. Unfortunately, that breaks ```manage.py migrate``` later on. I don't see badgecheck on the badgr-server repository - is it available publicly somewhere else? Or will you just remove it from being called by manage.py?

**Comment by ottonomy** [comment]
This requirement has now been removed from the dependencies file and is not required to migrate, open a management shell or run the development server. Thanks for your patience and sustained interest in the project. You should be all set now.
