### ISSUE TITLE
Python 2 end of life ?

### ISSUE THREAD

**Issue by stephanepoinsart** [concentricsky/badgr-server#208]
Hello,

On the main page of the project ( https://github.com/concentricsky/badgr-server ) and for the documented install commands, they seem to reference python 2.7.x as a requirement. As python 2 has been obsoleted since 01/01/2020, would it be possible to use python 3 to run badgr ?

Best regards,

Stephane

**Comment by shingom** [comment]
Django also should be updated to 2.2.
https://www.djangoproject.com/download/

**Comment by stephanepoinsart** [comment]
I latter noticed that @garrettseward have opened a pull-request about it, so we can be hopeful that this issue is being worked on : https://github.com/concentricsky/badgr-server/pull/218

Thanks for your efforts.

**Comment by ottonomy** [comment]
Yep, this is being worked on in the branch you referenced. This branch passes tests as of now, so you could take it and use it. We expect to have that merged into develop and then master in 4-6 weeks as we finish up some other upstream work that enables us to deploy the python3 version to our systems.
