### ISSUE TITLE
Installation notes are wrong

### ISSUE THREAD

**Issue by teopost** [concentricsky/badgr-server#21]
I followed the installation notes on a new machine with Ubuntu 14.0, but I found several errors

- git clone git@github.com:concentricsky/badgr-server.git code

The above command don't work. It return this error:

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````
- pip install -r requirements-dev.txt

return this error

```
......
Cleaning up...
Command /usr/bin/git clone -q ssh://git@stash.concentricsky.com/bp/badgecheck.git /tmp/pip-IWcR44-build failed with error code 128 in None
Storing debug log for failure in /home/user/.pip/pip.log
```

**Comment by ottonomy** [comment]
Thanks for the report. The published clone command assumes the user has set up an SSH key. I'll switch it to an HTTPS-based clone in the instructions.
