### ISSUE TITLE
Error in pip install -r requirements.txt

### ISSUE THREAD

**Issue by matty111** [concentricsky/badgr-server#211]
Hi,

when i run command "pip install -r requirements.txt" there are some error of python in a centos 7 machine.

**Comment by shingom** [comment]
Like this?
ERROR: pyopenssl 19.1.0 has requirement cryptography>=2.8, but you'll have cryptography 2.3 which is incompatible.

**Comment by matty111** [comment]
Yes i have update pip with 8 version and I solved

Cordiali Saluti,
Pasquale

________________________________

**Comment by matty111** [comment]
when I create an user i have an html error but in the staff console the user is created,
When i log in with this user i have this error: 
                            " Your session has expired. Please log in to continue."
When i am superuser instead i can log in without error

**Comment by shingom** [comment]
@matty111 
you have to verify the e-mail address.
usually, when you regist user, validation mail is sent to the email address.
but on local environment, you have to check verification via admin console.
<img width="1191" alt="スクリーンショット 2020-01-22 9 43 54" src="https://user-images.githubusercontent.com/9330478/72855838-33ff0e80-3cfc-11ea-9905-43af455cb710.png">

**Comment by matty111** [comment]
I suggest to modify the Readme file because is hard to know as it work. 
For example I stopped when I make "award badge" from Issuers
/issuer1/badges/badge1/Award Badge
this is the result.
![Capture](https://user-images.githubusercontent.com/58981392/72968289-7ccdca80-3dc3-11ea-8ea5-2d158ab0c9a5.PNG).
