### ISSUE TITLE
BadgrApp matching query not exists

### ISSUE THREAD

**Issue by matty111** [concentricsky/badgr-server#215]
I'm working with master's branch of badgr-ui and badgr-server.

**Comment by shingom** [comment]
maybe this is useful.
https://badgr.org/hosts/#production

**Comment by matty111** [comment]
but it's correct to use these version? Master of badgr-server and master of badgr-ui.

**Comment by shingom** [comment]
maybe this section.
"Badgr App Configuration"
https://github.com/concentricsky/badgr-server/blob/develop/README.md

**Comment by matty111** [comment]
I solved. In http://localhost:8000/staff/mainsite/badgrapp/add/ I added:
CORS: ensure this setting matches the domain on which you are running badgr-ui, including the port if other than the standard HTTP or HTTPS ports. localhost:4000
Signup redirect: http://localhost:4000/signup/
Email confirmation redirect: http://localhost:4000/auth/login/
Forgot password redirect: http://localhost:4000/change-password/
UI login redirect: http://localhost:4000/auth/login/
UI signup success redirect: http://localhost:4000/signup/success/
UI connect success redirect: http://localhost:4000/profile/
Public pages redirect: http://localhost:4000/public/

Last question. In "Oauth authorization redirect" of this page what can i insert?

**Comment by ottonomy** [comment]
@matty111 for `oauth_authorization_redirect` you can use `http://localhost:4000/`.

I'll file a related ticket to clean up the list of these and provide better documentation around how they are used.
