### ISSUE TITLE
Struggling and need some help

### ISSUE THREAD

**Issue by jniven** [concentricsky/badgr-server#220]
Im having a tough time trying to get a fully functional badgr-server and badgr-ui up and running.

My setup, currently for testing is Centos7 in VMware workstation

Have followed the instructions to install badgr-server and badgr-ui and all appears to be installed correctly, at least no errors seen.

As this is a VM with no Xserver running, and im not really wanting to have to setup ssh tunneling etc, Im looking to access the server and ui over the IP address of the host and not localhost.

I have setup /etc/hosts to resolve domain to its own IP and setup my client hosts file to also point to same IP. Resolution is working as expected.

Updated settings_local.py

HTTP_ORIGIN = 'http://mydomain:8000'
ALLOWED_HOSTS = ['*']  (This is only for testing and to rule out any issues with hosts)

So to some of my issues...

I am starting the server with ./manage.py runserver 0.0.0.0:8000 as this seems to be the only way i can get a listener on the IP and not just localhost.

When browsing to my http://mydomain:8000/staff I can login etc, but the display is out of whack as it doesnt seem to be getting the CSS files correctly. When looking at the request, its trying to get them from localhost (GET http://localhost:8000/static/admin/css/base.css net::ERR_CONNECTION_REFUSED)

I dont know where it is getting this from. Obviously the host is not able to resolve localhost to the remote server.

The second issue is I "think" im setting up the Badgr App correctly, however im getting the following issue when using the badgr-ui

My badgr-ui is running on port 80. What should my Badgr app urls be assuming my domain is mydomain,com.

When i browse to http://mydomain.com it redirects to http://mydomain.com/auth/login. I can then login. If however I type http://mydomain.com/auth/login into the web broswer directly it errors with "The requested URL /auth/login was not found on this server."  I dont know much about CORS, so i dont know if this is normal or not?

I can do everything in the UI perfectly fine, ive created an issuer, and certs, and awarded a cert, however when i try to view the cert i then get The requested URL **/public/assertions/0mU6XzJ2RKWolbTPjrUTCg was not found on this server.**

Honestly, I think Im really close to having a fully working system and I know its just something small im missing, but im stuck.

Im also trying to setup email without much succes using EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

Im not 100% sure where i should put 

EMAIL_HOST= ''
EMAIL_HOST_USER= ''
EMAIL_HOST_PASSWORD= ''
EMAIL_USE_TLS= 
EMAIL_PORT= 

Ive put it in settings_local.py but it doesnt seem to work, or i may have a whole setup peice im missing on that but just cant find any info on it and my Django skills are non existent tbh.

Sorry, i know this is a rambling of stuff, but just seems a lot of little things, :-(

**Comment by ottonomy** [comment]
> Obviously the host is not able to resolve localhost to the remote server.

What does this mean to you? What is the "host" and the "remote server" in this context?

It seems like you could adjust your static files django settings to match where you have deployed them on this domain. 

https://docs.djangoproject.com/en/1.11/howto/static-files/

**Comment by jniven** [comment]
sorry Ottonomy, i meant of course my "client" is not able to resolve "Localhost" to the server running badgr-server as localhost is different in the clients context.

As I said, django isnt my forte, i wouldnt really know where to start changing whatever needs changing without some pointers. Like, where is it getting localhost:8000 from?

**Comment by ottonomy** [comment]
Check out the link above and the `STATIC_URL` setting specifically. A relative url starting with `/` should be safe. 

Runserver is not suitable for production, so take a look at the WSGI-based deployment guides here to get Django served by Apache or another production-ready web server application: https://docs.djangoproject.com/en/1.11/howto/deployment/

**Comment by jniven** [comment]
I was hoping i wouldnt need to learn django ijust n order to run this tbh :-S I was looking for more of a turnkey solution, which maybe this isnt in that case. I was sort of looking for something i could just follow along with to install.

**Comment by jniven** [comment]
So the static url helped with the first part, but the other stuff is still the same. It seems to be anything with redirects which makes me think its the badgr-app settings.

**Comment by jniven** [comment]
Ok still have the issues but i think i can see why, but i dont know how to fix it. When I try to view the badge the url goes to http://mydomain.com/public/assertions..... but shouldnt this be the badgr-server port... ie for me http://mydomain.com:8000/public/assertions....

if i curl the first url i get 404 not found.... if  run the curl against the same url but use port 8000 (badgr-server port) i get the correct json returned.

It seems to be that the badgr-app public redirect is the part that rewrites the url from the port:8000 url to the one without because thats what i belive should be in there (the badgr-ui server & port). If i change this to be the badgr-server url and port...it fails with "too many redirects". Can anyone share any light on this and what the expected behavior is?

**Comment by jniven** [comment]
Just in case anyone else comes across this... it was the mainsite/settings.py that also have the HTTP_ORIGIN set to localhost:8000 changed that and everything started working.
