### ISSUE TITLE
Disable DEBUG breaks Badge viewing

### ISSUE THREAD

**Issue by jniven** [concentricsky/badgr-server#225]
I finally got round to disabling DEBUG in settings_local.py

When i set to DEBUG = False

Badge Images are no longer viewable 

"GET /media/uploads/badges/assertion-1SBDbzN7TOuQw4w5WnUXdA.png HTTP/1.1" 404 2063

with DEBUG = True

"GET /public/assertions/1SBDbzN7TOuQw4w5WnUXdA HTTP/1.1" 302 0

Any ideas why DEBUG would have this impact?

**Comment by ottonomy** [comment]
You're getting different URLs in these different cases. The latter should (and is correctly) return a 302 to the ui for a `Accept: */*` or `Accept: text/html` context. The former is a media path if you have your django configured to serve locally hosted media.

**Comment by ottonomy** [comment]
Feel free to reopen if you reproduce with identical URLs in the format of the first (a media URL)
