### ISSUE TITLE
Log badge deletion events

### ISSUE THREAD

**Issue by louisconcentricsky** [concentricsky/badgr-server#240]
## System information & context:
- Badgr server logging

## Description of issue or feature request, including any error messages:
Badge deletion events are not logged. The event `badgrlog.events.issuer.BadgeClassDeletedEvent` should be triggered when a badge deletion occurs. A TODO note was left in `issuer.api.BadgeClassDetail.delete`

---
Notes (safe to delete):

It would be a great bonus to audit the other events in the `badgrlog` app to make sure they are triggered at appropriate times.

**Comment by snehalbaghel** [comment]
@louisconcentricsky I'd like to work on this. I'll try to submit a PR soon.

**Comment by EUGINELETHAL** [comment]
Am an Outreachy applicant looking for issues to work on?KIndly advise me
