### ISSUE TITLE
Started server, but connection requests are immediately rejected

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#25]
I am not exactly sure why the server is rejecting requests. The logfile is completely empty. The only clue I have at the moment is that some file cannot be found, but I am not sure which file manage.py is looking for.

./manage.py runserver seems to work fine (no errors reported). However:
(env)[cschultz@badgekit code]$  ./manage.py dist
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cschultz/badgr/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/cschultz/badgr/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cschultz/badgr/env/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/cschultz/badgr/env/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/cschultz/badgr/code/apps/mainsite/management/commands/dist.py", line 32, in handle
    ret = call(['grunt', 'dist'])
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I installed both grunt and dist (dist was not listed as a prerequisite) and I see them in the node_modules directory:
(env)[cschultz@badgekit code]$ ll /home/cschultz/badgr/code/node_modules/dist /home/cschultz/badgr/code/node_modules/grunt
/home/cschultz/badgr/code/node_modules/dist:
total 12
drwxrwxr-x. 2 cschultz cschultz   20 Oct 21  2012 bin
-rw-rw-r--. 1 cschultz cschultz  200 Oct 21  2012 HISTORY.md
drwxrwxr-x. 2 cschultz cschultz   20 Oct 21  2012 lib
-rw-rw-r--. 1 cschultz cschultz 1716 Dec 14 18:18 package.json
-rw-rw-r--. 1 cschultz cschultz    7 Oct 21  2012 README.md
drwxrwxr-x. 3 cschultz cschultz   57 Dec 14 18:18 test

/home/cschultz/badgr/code/node_modules/grunt:
total 20
-rw-rw-r--. 1 cschultz cschultz 1242 May  9  2014 appveyor.yml
-rw-rw-r--. 1 cschultz cschultz  127 May  6  2014 CONTRIBUTING.md
drwxrwxr-x. 2 cschultz cschultz   38 Dec 14 18:18 internal-tasks
drwxrwxr-x. 4 cschultz cschultz   44 Dec 14 18:18 lib
-rw-rw-r--. 1 cschultz cschultz 1062 May  6  2014 LICENSE-MIT
drwxrwxr-x. 5 cschultz cschultz   44 Dec 14 18:18 node_modules
-rw-rw-r--. 1 cschultz cschultz 2837 Dec 14 18:18 package.json
-rw-rw-r--. 1 cschultz cschultz  900 May  6  2014 README.md

**Comment by sacrophyte** [comment]
Also, it does not seem that the port number in apps/mainsite/settings_local.py is being respected. In particular, I set the port to 8080, yet the server always starts on port 8000

(env)[cschultz@badgekit code]$ grep 8080 apps/mainsite/settings_local.py
HTTP_ORIGIN = 'http://localhost:8080'

(env)[cschultz@badgekit code]$  ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
December 14, 2015 - 10:55:30
Django version 1.7.1, using settings 'mainsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[cschultz@badgekit code]$ sudo netstat -tanp|grep 80
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      4718/python

**Comment by sacrophyte** [comment]
Per email with Nate, I think we got to the bottom of this. I was not aware of this, but apparently the above shows that the server is only listening for local requests. To open it to the world, I have to do the following:

(env)[cschultz@badgekit code]$ python ./manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
December 14, 2015 - 11:25:07
Django version 1.7.1, using settings 'mainsite.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

**Comment by ottonomy** [comment]
Yep, thanks for the discovery. As noted in the [Django docs](https://docs.djangoproject.com/en/1.7/ref/django-admin/#runserver-port-or-address-port), runserver (which is not intended for production use; just testing. We recommend using Apache with mod_wsgi or similar to host the application for production use) does not listen for external requests by default. 

Some users have indicated that starting the command as we recommend with `./manage.py runserver` does not allow external traffic even if you specify the ip:port as described in the documentation, but that if you use `python ./manage.py runserver 0.0.0.0:8000` you can successfully listen from outside.
