### ISSUE TITLE
Fetching the badgeclass returns "entity not found or insufficient privileges"

### ISSUE THREAD

**Issue by pixeline** [concentricsky/badgr-server#252]
## System information & context:
- Operating system you are using: Mac OS X  / Terminal
- Browser & version: using the terminal
- URL or path of the screen where you encountered this issue:

https://api.badgr.io/v2/badgeclasses/5e67af813ed4bb5c1e675b69

## Description of issue
I would like to programatically validate the badge entityId encoded by our CMS user.
The user provides the hash via a form, clicks submit, my PHP script needs simply to send it to badgr.io api server and according to the response status code, decides if it is valid or not.

Problem: no matter what I enter, the badgr API returns an error: "**entity not found or insufficient privileges** "
I tried using curl via the Terminal, just to make sure my code is not the culprit
The bearer token is correct, and I'm the Issuer Owner, so it's not an authentication or privilege issue. 
The badgeClass exists (here it is, public url: https://badgr.com/public/badges/WwglTWvWR-ixA28XCS2ykg)

Example (redacted to hide the token):

```bash
curl -X GET "https://api.badgr.io/v2/badgeclasses/5e67af813ed4bb5c1e675b69" 
       -H "accept: application/json" 
       -H "Authorization: Bearer my_token"
```
the response i get:

```json
{"status":{"description":"entity not found or insufficient privileges","success":false},"validationErrors":[],"fieldErrors":{},"result":[]}%
```

Really scratching my head here. Can you help me ?

**Comment by ottonomy** [comment]
@pixeline I think you got the entity Id wrong by copying it out of the URL bar on the front end. `5e67af813ed4bb5c1e675b69`. The correct entity id is in the other working URL you posted: `WwglTWvWR-ixA28XCS2ykg`

So update your request URL to `https://api.badgr.io/v2/badgeclasses/WwglTWvWR-ixA28XCS2ykg`

**Comment by pixeline** [comment]
@ottonomy argl, thank you. It makes sense in fact. Thank you for your help on this!
