### ISSUE TITLE
Suggestion: put contact email address in settings_local.py

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#26]
I found a contact email address (help@badgr.io) in context_processors.py - maybe it should be move to settings_local.py and pointed out as something the user should change? :)

**Comment by ottonomy** [comment]
The Badgr team help email is provided as a default in case the server administrator has not defined `HELP_EMAIL` in `settings_local.py`. 

The line in question is `'HELP_EMAIL': getattr(settings, 'HELP_EMAIL', 'help@badgr.io')`, which means that the code will inspect the settings as first resort, but will fall back to a real help address that our team is checking.

Please define the setting 'HELP_EMAIL' in your local settings, and your own help address will be reflected in relevant locations.

Cheers!
