### ISSUE TITLE
Is verification mail actually being sent?

### ISSUE THREAD

**Issue by sacrophyte** [concentricsky/badgr-server#27]
I see from my runserver output that a MIME email has been generated, but I never receive it. I did some simple email tests to myself and they are delivered with no problem. I have also been chacking my spam folder but nothing has showed up. Are these messages actually put into the mail queue (I do not yet know enough to know how to check)?

Also, how do I reset "example.com"? I have been searching through the source code and example.com is used a LOT, but I am not sure which one of them specifically sets it for the MIME message.

Here is the message from the runserver output (and yes, I redacted some of the names):

Content-Type: multipart/alternative;
 boundary="===============2386072405322112773=="
MIME-Version: 1.0
Subject: [example.com] Confirm Badgr Email Address
From: sacrophyte@gmail.xxx
To: sacrophyte@gmail.xxx
Date: Mon, 14 Dec 2015 20:54:23 -0000
Message-ID: <20151214205423.6338.98597@xxxx.xxxxx.xxxxx.xxxx>

--===============2386072405322112773==
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

User sacrophyte@gmail.xxx at example.com has given this as an email address.

**Comment by sacrophyte** [comment]
There is no indication that email was attempted to be delivered via /var/log/messages or  /var/log/maillog. I do see entries for my own test, but nothing that corresponds to badgr saying it sent a verification email.

**Comment by ottonomy** [comment]
@sacrophyte The default settings for email are to use console output. This is set by the `EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'` line in `settings_local.py.example`. You can make the server actually send mail by filling in credentials for a real mail server. [See Django documentation here](https://docs.djangoproject.com/en/1.7/topics/email/).

Example settings for a recommended email backend, the AWS Simple Email Service are stubbed out in the `settings_local.py.example` file.
