### ISSUE TITLE
Typo in the file apps/issuer/serializers_v2.py

### ISSUE THREAD

**Issue by TheophileDiot** [concentricsky/badgr-server#296]
## Description of issue or feature request, including any error messages:

Hi, while I was translating the files I came across this line 659 typo in the ValidationError message.

![Typo](https://user-images.githubusercontent.com/57175294/86333665-80a42980-bc4c-11ea-972e-1fd05adafa1e.png)

Unless I am mistaken, I think that the word should be : **class**

**Comment by ottonomy** [comment]
Thanks. Fixed in PR #298
