### ISSUE TITLE
Invalid Assertion Structure with Mozilla Backpack

### ISSUE THREAD

**Issue by Kelketek** [concentricsky/badgr-server#3]
When attempting upload a badge generated with badgr-server to Mozilla Backpack while Badgr-server is running, Mozilla Backpack will contact Badgr-server to verify the assertion, and will fail saying 'Invalid Assertion Structure'.

Example baked image:

http://sandbox.opencraft.com:8005/media/issued/6e8a96230ffe4b96179d8ef5b405c5d1.png

**Comment by ottonomy** [comment]
It needs a 'uid' field. I've got this fixed but not released. I'll push a new version shortly for you.

**Comment by ottonomy** [comment]
This should be fixed in b5a3ba2330

**Comment by Kelketek** [comment]
@ottonomy I can't verify this because Backpack is down. Do you know someone we can bother at Mozilla to get it up and running again?

**Comment by Kelketek** [comment]
@ottonomy Backpack is back up and allowing badge submissions, but it's still giving the Invalid Assertion structure message. I checked the baked badge in a hex editor, and the UID field is there now, so there must be something else.

**Comment by ottonomy** [comment]
Hmm, I am getting all green lights on the badges I'm producing. Use http://validator.openbadges.org to get accurate error messages. If you can give me the URL of an assertion, I can assess it for you.

**Comment by Kelketek** [comment]
@ottonomy The assertion is at http://sandbox.opencraft.com:8005/public/assertions/aa935ca3-b423-499a-b0f7-aed6e64bfcc9

**Comment by ottonomy** [comment]
The description in the BadgeClass JSON is null, and it must be a string. I'm curious how you created this BadgeClass model instance. If you did it through the API, the serializers should have caught the omission. Description is a required property. I'll see if I can duplicate this issue when creating a BadgeClass.
