### ISSUE TITLE
sass compile error on build/scss/screen.scss

### ISSUE THREAD

**Issue by tadesanya** [concentricsky/badgr-server#30]
Syntax error: Invalid CSS after \"  bodybackground\": expected \")\", was \": #F5F5F5,\"\n on line 2 of build/scss/_base.scss\n

**Comment by ottonomy** [comment]
Hi, sorry we missed this issue report for so long! What version of sass do you have installed on this machine? (What operating system are you using?)

Are you encountering this error when you run grunt? Any other information you can provide about when you are encountering this problem would be helpful. Thanks, @andela-tadesanya !

**Comment by ottonomy** [comment]
The most recent version v1.1.10 included a fix for a unicode character appearing in one of the scss files, though that problem may be unrelated to the issue you're encountering. Let us know if this issue is solved for you.

**Comment by bryanlandia** [comment]
@andela-tadesanya You probably have an older version of Sass installed.  You can fix this by getting Sass 3.3+

**Comment by ottonomy** [comment]
The build process in which this issue occurred has moved to the badgr-ui application and has been updated. SCSS compilation is handled by the webpack build process there, in part.
