### ISSUE TITLE
Docker installation problems localhost forced

### ISSUE THREAD

**Issue by cdisabatino** [concentricsky/badgr-server#303]
## System information & context:
- Operating system you are using: CentOS Linux release 7.8.2003 (Core)
- Browser & version: Firefox 78.0.2 (64 bits)

## Description of issue or feature request, including any error messages:
I tested the complete installation several times with Docker. Both modes, development and production. Each time I have the same problem. Some requests are forced to "localhost:8080". I tested several modifications but nothing works. I changed ".docker/etc/settings_local.prod.py". I tried to install Nginx to do reverse proxy. But it doesn't work either.
Even in development mode, configured by default with port 8000, there are forced requests in 8080.

Before the version with Docker, I managed to make bardg-server work properly.

What should I change to access with a DNS name different from localhost ?

Thank you

Default address :
![docs](https://user-images.githubusercontent.com/46713357/87794276-ab929e00-c846-11ea-9873-401f3c73eae4.png)

Staff address :
![staff](https://user-images.githubusercontent.com/46713357/87794245-a6355380-c846-11ea-92ce-7f5f7881d111.png)

**Comment by snehalbaghel** [comment]
I was facing a similar issue. If you're using the example dev settings file make sure that you have changed the HTTP_ORIGIN to 'http://localhost:8000'.

**Comment by cdisabatino** [comment]
> 
> 
> I was facing a similar issue. If you're using the example dev settings file make sure that you have changed the HTTP_ORIGIN to 'http://localhost:8000'.

Unfortunately I have already tried to change the value of HTTP_ORIGIN. For both modes. Without success. I even tried to enter the final hostname of the application.

Today, is your application functional with this docker version ? Are you using a hostname other than localhost to access the app ?

Thank you,
Christophe

**Comment by snehalbaghel** [comment]
Yeah, it's working for me. I remember it broke a couple of weeks ago but #302 fixed it. The only change I needed to make was the one I mentioned above. Maybe try pulling the latest changes and `docker-compose up --build`

**Comment by cdisabatino** [comment]
My bad.

For my first test, in the `settings_local.dev.py` and `settings_local.prod.py` files I had to leave localhost. With Docker, anonymous volumes are created. I hadn't seen him. By removing anonymous volumes it works :
`docker volume ls`
`docker volume rm code_badgr_server_prod_db code_badgr_server_api`

After removing the volumes and rebuilding the application, the database migration is performed again `migrate`.
Simple rebuild does not take the new address of HTTP_ORIGIN. The hostname may be saved in the database at the time of the migrate ...??...

After, in production mode, in addition to the doc, I execute the following commands :
`docker-compose -f docker-compose.prod.yml exec api python /badgr_server/manage.py dist`
`docker-compose -f docker-compose.prod.yml exec api python /badgr_server/manage.py collectstatic`
`docker-compose -f docker-compose.prod.yml exec api python /badgr_server/manage.py createsuperuser`

Now badgr-server is working fine with docker and a hostname different from localhost (HTTP_ORIGIN == http://myHOST:8080)

Thanks you
Christophe
