### ISSUE TITLE
Unable to configure formatter 'json'

### ISSUE THREAD

**Issue by kmuston** [concentricsky/badgr-server#32]
When attempting to run ./manage.py migrate, I receive the following message. 
ValueError : Unable to configure formatter 'json': Cannot resolve 'mainsite.formatters.JsonFormatter': cannot import timezone

I can't seem to get past this point.

**Comment by ottonomy** [comment]
@kmuston This seems to be an issue with your Python environment and django setup. I have a few questions that could help you move forward.

* Could you share details of your environment (operating system, virtualenv setup)?
* Did you use virtualenv to segment the python/django tools for this install from those for your "system python" version? 
* Were there any issues running `pip install -r requirements-dev.txt`? 
* Did you "activate" the environment before attempting to run the migration code?
