### ISSUE TITLE
Badge classes and instances

### ISSUE THREAD

**Issue by josmas** [concentricsky/badgr-server#33]
Hi guys, apologies if this is not the place to ask questions; couldn't find any other way to reach out.

Everything seems to work fine locally, but we are only able to create **badge classes** and not _instances_. In your server, after creating an issuer and adding a badge, it creates that _badge class_ and automatically appears in the list of active badges that can be issued as an instance directly from the list itself. Locally though, after creating an issuer and a badge, the badge does not appear in the listing for the issuer (we can only see badges in the staff/admin section), so we cannot issue them as badge instances from the interface. Is this by design?
I have changed all kinds of permissions but still cannot see the badges in the list. Even in the staff section, there is no _Add_ button for badge instances (there are _add_ buttons for everything else).

Any ideas or pointers about where to look? I may be missing something in the spec, but can't find any docs here, so it's quite possible I am misunderstanding something.

We are looking into migrating [PaperBadger](https://github.com/mozillascience/PaperBadger) to using Badgr cc/ @ottonomy @acabunoc @jinankjain

**Comment by ottonomy** [comment]
@josmas Thanks for asking. Are you using hosted badgr.io or a self-hosted install of the open source version? (if so, which code version?)

On the BadgeClass Detail Page in the front end (URL scheme like: /issuer/issuers/kitten-appreciation-club/badges/level-2-cat-fancier ), there is an Issue Badge button in the upper-right. We are redesigning some of our button patterns to make them more apparent. 

From the Issuer Detail page listing BadgeClasses, there should be an Issue button in the table row for each BadgeClass. Could you share a screenshot perhaps showing how your page is rendered so I can help you locate the feature or identify if there is a bug in effect?

**Comment by ottonomy** [comment]
Connected with this user off-channel. For future users encountering this issue, make sure your HTTP_ORIGIN is set in `mainsite/settings_local.py`, and do not change this value over the course of operation of the server.
