### ISSUE TITLE
Failed to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by nasirkhan** [concentricsky/badgr-server#34]
## System information:
- Operating system you are using: Ubuntu 16.04 
- Browser & version: https://aboutmybrowser.com/pH6DF4H3
## Description of issue, including any error messages:

I tried to install the Badgr Server and following the instructions from https://github.com/concentricsky/badgr-server. At the time of running the command `pip install -r requirements-dev.txt` i got an error and the install was not completed. you can get the complete log at http://paste.ubuntu.com/18817240/

**Comment by josmas** [comment]
@nasirkhan It seems that your system is missing some libraries. Have you installed `libmariadbclient-dev` or the _MySQL_ or _MariaDB_ packages for your distribution?
It works for me on Ubuntu __14.04__ but haven't tried __16.04__.

**Comment by sariabod** [comment]
Just making a note in case anyone else has this issue. On ubuntu 16 you will need to install `libmysqlclient-dev` even if you use mariadb.

**Comment by OLFASALAH** [comment]
Me too, it does not worked in 16.04 LTS 
I have this issue 
Command "/edx/app/edxapp/badgr/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RH_Gxp/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2dq4P9-record/install-record.txt --single-version-externally-managed --compile --install-headers /edx/app/edxapp/badgr/env/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-RH_Gxp/cryptography/

**Comment by ottonomy** [comment]
Cryptography is often a python package that takes a little extra work to install on a particular system. If you are having trouble using the suggested `pip install -r requirements.txt` method, I suggest working through a `pip install 'cryptography==2.3.1'` separately (we'll be upgrading from 2.2.2 to 2.3.1 imminently)
