### ISSUE TITLE
unable to continue on step ./manage.py migrate: no module named kombu.five

### ISSUE THREAD

**Issue by hamrt** [concentricsky/badgr-server#35]
## System information:
- debian 8.4:
- Browser & version:
## Description of issue, including any error messages:

On trying to run ./manage.py migrate I get the following error 

![image](https://cloud.githubusercontent.com/assets/20848554/17466522/1af82462-5d12-11e6-8004-b915208cf2dc.png)

is this a debian related issue?

**Comment by kamaradclimber** [comment]
@hamrt apparently you have to add 

> kombu==3.0.12

in the requirements.txt and rerun pip install -r requirements-dev.txt

I had a second similar issue that required to add billiard in the same file.

**Comment by ottonomy** [comment]
kombu is no longer required (unless you are overriding `CELERY_ALWAYS_EAGER = True` to run your own asynchronous task processing). Task processing in badgr-server is minimal, but the options to process certain tasks async is available, and the types of tasks that should be processed outside the context of a web request (by the web application) may grow in the future to include more operations that impact the average badgr-server implementer.
