### ISSUE TITLE
verification email

### ISSUE THREAD

**Issue by jbolesec3** [concentricsky/badgr-server#36]
## System information:
- Operating system you are using: ubuntu 12.04
- Browser & version: firefox
- URL of the page where you encountered this issue:
- If your issue refers to the Badgr app in the Canvas LMS, the url of your canvas server or course where the problem occurred.
  - Course URL: 
## Description of issue, including any error messages:

i install badgr server on Ubuntu 12.04 and run server on port 9000 but when login he send me verification email but there is no email reach to my inbox any idea about the problem ??

You can also [add a screenshot](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) or [add a file](https://github.com/blog/2061-attach-files-to-comments)

**Comment by josmas** [comment]
Hi @jbolesec3 

If you look at the output in the terminal in which you are running `./manage.py runserver` you will see the template of the email that is sent when a proper email server is configured. From there you could copy the url, which should look something like `http://localhost:8000/accounts/confirm-email/dmrfdccwdnxpqdyiqxxxxxidjiaodfnoeb66dgcbwqqutzkjiay8hkrc6lbdollmfi/` and paste it directly in your browser to verify your _superuser_ or other accounts.

Note: I am not part of the _badgr_ team, but that works for me.

**Comment by nguyentrung0904** [comment]
It woked

**Comment by ottonomy** [comment]
Thanks for the assist, @josmas. The default email backend is indeed a terminal stdout backend. When deployed to the web, this should be overridden in settings_local with the correct email backend. SMTP, Amazon SES, and more are options for deployed versions of Badgr. 

Here is some information about email backends in Django: https://docs.djangoproject.com/en/1.11/topics/email/#email-backends
