### ISSUE TITLE
How to edit a badge

### ISSUE THREAD

**Issue by fzavat** [concentricsky/badgr-server#38]
## System information:
- Operating system you are using: Mac 10.10 Yosemite
- Browser & version: Safari 9.1
- URL of the page where you encountered this issue: webpage where I tried to edit => https://badgr.io/issuer/issuers/francesco/badges/badge1-2 
## Description of issue, including any error messages:

Hi. Just testing your server software on the website for the very first time. I add an issuer and then a I add a badge. I see the badge properly (active). However, once created,  it does not seem possible  to edit and modify the badge. Do I miss something? 
(I also revoked the badge to the recipients but the behaviour did not change)

By the way what I was trying to achieve was  to link some keywords to this new badge. So I tried  to edit  the "criteria" field for this purpose. Is it the right way to proceed?

Thank you
Nice work
Francesco

**Comment by ottonomy** [comment]
This feature will be added shortly. API endpoints on api.badgr.io have been created if you have any feedback about this feature. When the next open source release is ready, it will be posted here.
