### ISSUE TITLE
Verify Badge with blockchain

### ISSUE THREAD

**Issue by matty111** [concentricsky/badgr-server#384]
Hi guys,

I have seen there are other badges that use blockchain to verify. 
With this project is possible verify those badges? for example  https://www.accredible.com/

With https://badgecheck.io/ I can't verify the badges of Accredible.

There are solutions?

Thank you :)

**Comment by ottonomy** [comment]
Hi, @matty111.

Badgr doesn't currently offer a "put a hash of this badge on a blockchain" feature, though our team is active in various communities in which we are examining the next generation of credential verification technologies. You can expect to see some new offerings in the category of cryptographic proofs on credentials issued by Badgr and importable to Badgr in the not too distant future.

The purported advantages to "trust" of involving a blockchain in credential verification don't always shake out, at least when considering the "put a hash of this thing on a blockchain somewhere" use case. Those prototype implementations that are available on the market today aren't standardized at a high level, so validators like the IMS Global Open Badges Validator (and the copy of that we run at https://badgecheck.io) don't implement those techniques at the moment. For some more reading on the topic, consider https://www.concentricsky.com/articles/detail/is-blockchain-ready-for-prime-time-in-education

Also if you're interested in getting involved in the next advancements with cryptographically-verifiable digital credentials, consider joining us at the Verifiable Credentials Community Group at the W3C. It's free to join. https://www.w3.org/community/credentials/ You may reopen this if you've got more questions here.
