### ISSUE TITLE
Can not award recipient by curl

### ISSUE THREAD

**Issue by mecycle** [concentricsky/badgr-server#399]
## System information & context:
- Operating system you are using: windiws
- Browser & version: Chrome

## Hi there, can anyone tell me why my POST request does not work? I try to use "badgeclasses/{badge class Id}/assertions" and always get the same error 

Here is what I am doing:
![image](https://user-images.githubusercontent.com/53304036/132606437-23c998a5-67c2-4f04-a554-6df23fe712d7.png)

This is the error:
![image](https://user-images.githubusercontent.com/53304036/132606490-4d2ce19d-ab3d-4a20-b545-07fd41e83b96.png)

I am not sure why this error, I think I added the recipient information.

Thanks.

**Comment by ottonomy** [comment]
The server can't tell what data type your POST body is, so you should add a `Content-Type` header. By default, you're passing this request to the server using the content-type `application/x-www-form-urlencoded`. Here's an example of a working request in curl:

```
curl --location -g --request POST 'https://api.au.badgr.io/v2/badgeclasses/{{badgeclass_entity_id}}/assertions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{auth_token}}' \
--data-raw '{
  "recipient": {
    "identity": "testrecipient3f023cf8-02ae-4b82-b6b4-43c6718f48d7@mailinator.com",
    "type": "email",
    "hashed": true
  }
}
'
```

See note on this example's use of `--data-raw` (there is special handling of the `@` character in `-d`/`-data`
https://curl.se/docs/manpage.html#-d
