### ISSUE TITLE
Instructions for installing grunt

### ISSUE THREAD

**Issue by natea** [concentricsky/badgr-server#40]
## System information:
- Ubuntu 12.04
## Description of issue, including any error messages:

I'm trying to install Badgr, and when I get to the step to run grunt dist, this is what happens:

```
(env)vagrant@precise64:/edx/app/badgr/code$ grunt dist
No command 'grunt' found, did you mean:
 Command 'grun' from package 'grun' (universe)
grunt: command not found

(env)vagrant@precise64:/edx/app/badgr/code$ sudo npm install grunt
npm WARN package.json Badgr@1.1.10 No repository field.
npm WARN package.json events@1.0.2 events is also the name of a node core module.
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "grunt"
npm ERR! cwd /edx/app/badgr/code
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /edx/app/badgr/code/npm-debug.log
npm ERR! not ok code 0
```

In order to install Grunt, I had to make a new directory 'gruntinstall' and issue these commands:

```
root@precise64:/edx/app/badgr/code/gruntinstall# echo "{}" > package.json
root@precise64:/edx/app/badgr/code/gruntinstall# npm install grunt --save-dev
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
grunt@1.0.1 node_modules/grunt
├── path-is-absolute@1.0.0
├── grunt-known-options@1.1.0
├── eventemitter2@0.4.14
├── rimraf@2.2.8
├── exit@0.1.2
├── nopt@3.0.6 (abbrev@1.0.9)
├── minimatch@3.0.3 (brace-expansion@1.1.6)
├── glob@7.0.6 (inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.5, once@1.4.0)
├── findup-sync@0.3.0 (glob@5.0.15)
├── iconv-lite@0.4.13
├── coffee-script@1.10.0
├── grunt-cli@1.2.0 (resolve@1.1.7)
├── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)
├── js-yaml@3.5.5 (esprima@2.7.3, argparse@1.0.7)
├── grunt-legacy-util@1.0.0 (getobject@0.1.0, which@1.2.11, async@1.5.2, hooker@0.2.3, underscore.string@3.2.3, lodash@4.3.0)
└── grunt-legacy-log@1.0.0 (hooker@0.2.3, colors@1.1.2, underscore.string@3.2.3, lodash@3.10.1, grunt-legacy-log-utils@1.0.0)
```

**Comment by josmas** [comment]
Hey @natea 
not part of the badgr team here, just a user, but your _node_ version seems to be quite out of date
```
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
```

Note that _0.10_ is out of maintenance (and _0.12_ will be soon https://github.com/nodejs/LTS).
I have no issues with node version _5_. We have an automated docker setup that may be of help: [local-badgr-server](https://github.com/josmas/local-badgr-server).

**Comment by ottonomy** [comment]
Thanks for the correct comment, @josmas. We are currently using node 6.6+. 

On my development computer, I use [nvm](https://github.com/creationix/nvm/blob/master/README.markdown) to manage my active node versions. It's a little advanced, but if you need to work with many projects at once that may have varying (sometimes incompatible) node version requirements.

**Comment by ottonomy** [comment]
Grunt has now been removed from the build process. The front-end build process is now refactored into badgr-ui as webpack scripts initiated by npm.
