### ISSUE TITLE
Grunt dist no such file or directory

### ISSUE THREAD

**Issue by Darren95** [concentricsky/badgr-server#43]
## System information: 
- Operating system you are using: Centos 6.8

## Description of issue, including any error messages:

While trying to install Badgr on a linux server I have completed all the steps up to the point of database migration. I have run the ./manage.py migrate with no errors. I have also installed grunt on the system. However, when I try to run the grunt dist command I get an error No such file or directory: 'dist'. Here is a full list of the error message:

(env) [root@localhost code]# grunt dist
Traceback (most recent call last):
  File "/root/badgr/env/bin/grunt", line 11, in <module>
    sys.exit(main())
  File "/root/badgr/env/lib/python2.7/site-packages/grunt/render.py", line 94, in main
    render_from_file(**options)
  File "/root/badgr/env/lib/python2.7/site-packages/grunt/render.py", line 54, in render_from_file
    with codecs.open(input, encoding=encoding) as f:
  File "/root/badgr/env/lib/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'dist'

**Comment by ottonomy** [comment]
It looks like you have incorrectly installed grunt. Grunt should be installed with npm, not in the python environment. Grunt should be installed system wide (`npm install -g grunt`) and also locally (with `npm install`). 

Here are some instructions on how to install and use Grunt: http://gruntjs.com/installing-grunt

**Comment by Bjern** [comment]
In the end we resolved this error by installing grunt-dist (yum install grunt-dist)

Installing grunt alone is not enough.  It may be a Centos thing or latest npm thing, not really sure.  Feel free to close.

**Comment by ottonomy** [comment]
Grunt has now been fully removed from the codebase. The UI build tasks are in the companion repository badgr-ui and are managed as npm scripts that use webpack.
