### ISSUE TITLE
Command "python setup.py egg_info"

### ISSUE THREAD

**Issue by ianchesu** [concentricsky/badgr-server#44]
## System information: 
- Operating system you are using: Ubuntu 12.04
- Browser & version:
- URL of the page where you encountered this issue:
- If your issue refers to the Badgr app in the Canvas LMS, the url of your canvas server or course where the problem occurred.
    - Course URL: 

## Description of issue, including any error messages:
Command "python setup.py egg_info"

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lYPdBp/MySQL-python/

You can also [add a screenshot](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) or [add a file](https://github.com/blog/2061-attach-files-to-comments)

**Comment by ianchesu** [comment]
How can we solve this error?

**Comment by ottonomy** [comment]
@ianchesu I don't see the command `python setup.py egg_info` in our README. We use `pip install -r requirements` to install requirements. Perhaps this is the command you used when you encountered the error?

In any case, it appears that it is the MySQL connector that is not installing properly onto your system. Perhaps you could try to `pip install MySQL-python==1.2.5`  manually and resolve issues with that process outside of the broader `pip install` process that is part of installing Badgr.

**Comment by shivam3192** [comment]
whenever i am executing the command 
pip install -r requirements-dev.txt
i am getting the error 
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/34/1mgry6gs2ksf5w4t1v5lw9x40000gn/T/pip-build-P3q4MF/MySQL-python/

Now there is a point to this , my local machine has folders till /private/var/folders/34/1mgry6gs2ksf5w4t1v5lw9x40000gn/T/............

but pip-build and MySQL-python is nowgere to find
In addition to this the number after pip-build-****** are random that is with every error message they change

Now as per your solution i used pip install MySQL-python=1.2.5 and i am recieving the same error

Please
<img width="1280" alt="4" src="https://cloud.githubusercontent.com/assets/25085295/23934221/d78c80ec-0969-11e7-8eeb-3acb08f66c39.png">
<img width="1280" alt="5" src="https://cloud.githubusercontent.com/assets/25085295/23934250/0098b122-096a-11e7-89ee-474fc555368c.png">

 help

**Comment by ottonomy** [comment]
@shivam3192 My suggestion to directly use `pip install MySQL-python=1.2.5` was not a solution, directly. It's only a means to more closely identify the problem. 

The problem appears to be that mysql_config is not found. This could be because mysql is not installed on your system or because the mysqldb connector is not installed. 

Installation instructions for these features vary by system.  For example, see [this StackOverflow answer](http://stackoverflow.com/a/7475296/4427473).
