### ISSUE TITLE
Project is dead

### ISSUE THREAD

**Issue by Bjern** [concentricsky/badgr-server#46]
## System information: 
- Operating system you are using: Centos virtual machine on Windows 10 host
- Browser & version: Chrome and others
- URL of the page where you encountered this issue:  v1/issuer/issuers/{slug}/badges

## Description of issue, including any error messages:
This project is dead, no one replies to issues dating back to 2015 AND the code supplied here is horribly behind the real thing.  They have not supplied the latest code OR rather the version you see online is not what is here, and so there are many bugs.  We managed to get it going but can't even push badges with the API.  They get created but do not display under the issuer.

You're wasting your time if you want to use this for production.  It should be used as a concept only.

**Comment by ottonomy** [comment]
Hi, @Bjern. We are indeed actively developing badgr-server and are pushing new versions to our production server at [badgr.io](http://badgr.io/login). We will push updated versions to this repository as soon as we add another set of features and finish some refactoring. We expect a release in northern hemisphere summer this year. 

We are working with several contributing collaborators to gain early access to new versions of the code. Sorry this is not yet available to the general public. Feel free to email badgr@concentricsky.com if you have any questions or would like to talk about the early access program.

---
To your immediate issue:

Are the badges being properly returned from an API call to /v1/issuer/issuers/{slug}/badges and just not being displayed under the issuer in the interface? This likely indicates that there is a problem with the HTTP_ORIGIN setting making it so that the issuer JSON url in the BadgeClass is not matching the issuer "id" url from the Issuer record you've got. Perhaps you created the issuer, then changed the HTTP_ORIGIN setting, then created the BadgeClasses.

**Comment by Bjern** [comment]
No sorry not the issue.

We have confirmed that the HTTP_ORIGIN has never been adjusted or set any different.

The sql matches perfectly both issuer "id" and JSON url in badgeclass.
All API commands pushed are recorded in mysql.

The API does pull the badgeclass info of the badges under the issuer.
The API does save the issuer, the badgeclass and the assertion.
The API can return all these values.

The UI does show the issuer and logo under the issuers menus.
The UI DOES NOT show the badges under the issuer,
The UI DOES NOT show the assertions under the user when they are logged in.
You CANNOT add a badge from the UI even using the "Add badge" button.  It says successful and records it in mysql but never displays it under the Active badges table on issuer page.

We also issued a badge through the API.  We then pulled that image from the API and downloaded the "baked" image.  We then tested this image on multiple servers including badgr.io and mozilla backpack, none of them will import or upload or validate the badge.  So the issued badges seem to be a flop (baking pun intended).

**Comment by ottonomy** [comment]
@Bjern, is your development server behind a firewall that the Mozilla backpack/validator /badgr.io cannot access? Can you send me an assertion URL or paste assertion JSON here?

Feel free to open a support ticket by emailing help@badgr.io if you prefer.

**Comment by chamnap** [comment]
@ottonomy, Just a quick question.

Does [badgr.io](https://badgr.io) support Open Badges 2.0 Specification yet, https://openbadgespec.org/?

**Comment by ottonomy** [comment]
@chamnap, The IMS Global "Working Document" will be released at the Open Badges Working Group face to face meeting next week in Orlando. After that point, platforms will pledge to implement from the working document, and when at least two implementations (and some forthcoming validation work) are done, the 2.0 spec goes to the IMS Badges Executive Board for a finalization vote. Short story is that Badgr will be one of the platforms implementing this spec first, but we're waiting to start until next week. We've done some preliminary work around it, and we are deeply involved in the construction of the 2.0 validator, which will be integrated into Badgr.

**Comment by Bjern** [comment]
Thanks for all your help.  Nothing worked.

@chamnap badgr.io generates v1 spec.

I spent 3 days setting up a server.  I tried badger.io (this project) and the mozilla badgekit with absolutely no luck.  Before that we had spent a week trying a virtual machine, probably why it could not be verified as per your firewall comment.  I also found that neither system gave informative errors.  When I took my badges to openbadepassport.com I started getting errors "badge not owned by you", "badge has expired" etc...  unlike mozilla backpack "there was a problem".  What a lot of wasted time.

I really detest node.js and don't know why people use it (ignore my rant if you will). Both projects Github code is far behind and NOT usable.

In the end I spent 3 days writing a Laravel PHP website using Imagick and was able to bake a v2 openbadge accepted by all the platforms I had tested.  Tx for helping but I've moved on.

**Comment by chamnap** [comment]
@Bjern, actually, it has nice error message on the server if you inspected the network bar for different versions: 0.5, 0.5.1, and 1.0.

```code
{
  "message": "The uploaded badge did not validate.",
  "details": {
    "instance": {
      "BadgeInstanceSerializerV0_5": {
        "badge": {
          "issuer": {
            "org": [
              "This field may not be null."
            ],
            "contact": [
              "This field may not be null."
            ]
          }
        },
        "recipient": [
          "Enter a valid email address."
        ]
      },
      "BadgeInstanceSerializerV1_0": {
        "issuedOn": [
          "This field is required."
        ],
        "recipient": {
          "non_field_errors": [
            "Invalid data. Expected a dictionary, but got unicode."
          ]
        },
        "badge": [
          "Enter a valid URL."
        ],
        "uid": [
          "This field is required."
        ],
        "verify": [
          "This field is required."
        ]
      },
      "BadgeInstanceSerializerV0_5_1": {
        "badge": {
          "issuer": {
            "org": [
              "This field may not be null."
            ],
            "contact": [
              "This field may not be null."
            ]
          }
        }
      }
    },
    "badge_class": {
      "BadgeClassSerializerV1_0": {
        "issuer": [
          "Enter a valid URL."
        ]
      },
      "BadgeClassSerializerV0_5": {
        "issuer": {
          "org": [
            "This field may not be null."
          ],
          "contact": [
            "This field may not be null."
          ]
        }
      }
    },
    "issuer": {
      "IssuerSerializerV0_5": {
        "org": [
          "This field may not be null."
        ],
        "contact": [
          "This field may not be null."
        ]
      },
      "IssuerSerializerV1_0": {
        "url": [
          "This field is required."
        ]
      }
    }
  }
}
```
