### ISSUE TITLE
Stuck at "Badgr is Loading..."

### ISSUE THREAD

**Issue by AppLEaDaY** [concentricsky/badgr-server#47]
Though I apparently succeeded in installing Badgr, after launching the server with the command I mention below, upon successful login with an administration user I cannot go beyond the message mentioned in the subject. I've actually no familiarity with the software environment in use and I have no clue about where I could find some information about what's happening.

systemuser@hostname:~/badgr/code# ./manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
March 03, 2017 - 00:25:16
Django version 1.7.1, using settings 'mainsite.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
No handlers could be found for logger "django_auth_lti.middleware"
[03/Mar/2017 00:26:01] "GET / HTTP/1.1" 302 0
[03/Mar/2017 00:26:01] "GET /login HTTP/1.1" 302 0
[03/Mar/2017 00:26:01] "GET /accounts/login HTTP/1.1" 301 0

Besides I cannot tell what the "No handlers could be found" message is due to.

Would you help me, please?

Thanks in advance!

A.

**Comment by ottonomy** [comment]
@AppLEaDaY 

This does require an update to remove this from the default settings. This is a package that folks are having trouble installing with pip. We use it internally at CSky, but it is not used for badgr-server.

You can remove this from the MIDDLEWARE_CLASSES by overwriting it in your settings_local.py file.

Cheers! Let us know if you have more questions. I'll resolve this issue in a future commit.

**Comment by AppLEaDaY** [comment]
@ottonomy 
I'm not sure I did what you meant, anyway I commented out in apps/mainsite/settings.py
the line containing "django_auth_lti" and the mentioned error or warning disappeared.
I'm still stuck at the "loading". I cannot find any way to know what the server is doing while the browser is showing that message.

Any clue?

Thanks

A.

**Comment by ottonomy** [comment]
@AppLEaDaY: I recommend not editing settings.py but to add a line to your settings_local.py that overwrites the one in settings.py -- this will enable you to upgrade the code in the future more easily, because you wouldn't be making any changes to files that would get overwritten upon upgrade.

As to your "loading" message, you likely need to simply run `grunt dist` in your console. This will compile the front-end resources, including the ReactJS bundle that will render the site. Instructions are in the README.

**Comment by AppLEaDaY** [comment]
@ottonomy 
Thanks for the suggestion concerning the proper place to put my own settings: I created a MIDDLEWARE_CLASSES array in the settings_local.py file just for the purpose of omitting the django_auth_lti item and it did the job.

As for the "loading" message: I thought I issued the command you mentioned, still I run "grunt dist" anyway and I could see no error. The supposed temporary message is still there, though.
I don't know what I should see with the "/earner" path, anyway I see a "200" message...

[05/Mar/2017 02:02:08] "GET /earner HTTP/1.1" 200 3585

Another path that is producing the "loading" message is "/issuer".
Curiously enough I can access the dashboard by changing the path to "/staff" and there I can access what is showed. The REST interface is working as well. 

I hope somebody will help me to troubleshoot before I will learn something about Django framework.

Thanks anyway! :-)

A.

**Comment by ottonomy** [comment]
The loading message is almost certainly due to not having compiled front end resources. Could you open your Developer Tools in your browser to the Network tab and reload the page. Observe any 404's?

**Comment by AppLEaDaY** [comment]
I'm afraid that's not that evident: I find just 200 and 304 responses (not modified), that is no 404 at all.
I followed the installation instructions verbatim, I guess. I also went beyond them, struggling to get to the end without errors (though by now I can't recall all I did).

Thanks


A.

**Comment by ottonomy** [comment]
@AppLEaDaY Can you send a message to badgr@concentricsky.com so we can schedule a time to get on a screenshare with you. I'm sure we can help you get past this issue, but I'd rather do it in a synchronous manner so we don't go a couple days between attempts.

**Comment by AppLEaDaY** [comment]
@ottonomy Many thanks for your availability! :-) I'm going to let you know...

A.

**Comment by ottonomy** [comment]
It appears this user has made modifications to the package.json before running npm install, introducing peerDependency incompatibility between different ReactJS packages.

The README will be updated to include a recommended version of NodeJS to run (recent please: this app has been tested with 5.5 and 6.6).
