### ISSUE TITLE
After logging in I only see: Badgr is Loading

### ISSUE THREAD

**Issue by vanderheijden86** [concentricsky/badgr-server#48]
I am on OS X Sierra 10.12.1.

I followed all steps to get the server up and running. Set up a virtualenv, installed all with pip, ran npm start, installed mysql, created database, adjusted settings python file, ran the migrate command, and then runserver. I can login after I confirmed my email, but then I only get this: 

![image](https://cloud.githubusercontent.com/assets/16118904/24993145/632c0bc8-2025-11e7-9180-2fcac34f4750.png)

What could be wrong? Thanks a lot in advance!

**Comment by ottonomy** [comment]
Hi, @vanderheijden86. A necessary step is to compile the front-end Javascript and CSS. With the current version of the code, this is managed with the `grunt dist` *or `grunt watch` (for unminified local development) command.
