### ISSUE TITLE
USE_I18N: False

### ISSUE THREAD

**Issue by milovanderlinden** [concentricsky/badgr-server#49]
Really?

**Comment by ottonomy** [comment]
This project is migrating to a separate badgr-ui in Angular2+. Internationalization will be handled on the client side for now. We're open to coordinating with open source contributors to add internationalization capabilities to the application. Right now our immediate roadmap is pretty long and we haven't been able to start on it yet.

**Comment by milovanderlinden** [comment]
I have been breaking my neck over the various openbadges components. The mozilla stack is still node 0.10.x (I am trying to migrate one component at a time) and most front ends are either closed source or open source and not well documented. I have a use case in the Netherlands, but one thing I cannot have is an application that is not in dutch. What are the options for me to participate in badgr development?
