### ISSUE TITLE
Upgrading from Ubuntu 12.04?

### ISSUE THREAD

**Issue by mamigot** [concentricsky/badgr-server#51]
Hey Badgr,

Are there plans to upgrade the OS from Ubuntu 12.04 to 14.04 or 16.04, given that Ubuntu 12.04 is technically unsupported?

Thanks!

**Comment by ottonomy** [comment]
@mamigot nice to hear from you. Yes, we will update our Readme to describe the system(s) that we are actively using with the next release, coming this summer. The minimum system recommendations in the readme do not limit usability to those versions, they just describe some prerequisites that exist if you are using an OS in that family.

Are you encountering any issues running with the latest stable version of Ubuntu? We are currently deploying to images using a recent stable version of CentOS.
