### ISSUE TITLE
unable installing badgr-server

### ISSUE THREAD

**Issue by OLFASALAH** [concentricsky/badgr-server#54]
I followed these steps but while running this command " pip install -r requirements-dev.txt" i get this issue :
"Command "/edx/app/edxapp/badgr/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gtEfOL/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-HApR5v-record/install-record.txt --single-version-externally-managed --compile --install-headers /edx/app/edxapp/badgr/env/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-gtEfOL/cryptography/" 

I installed all package dependencies required and also the gcc version to gcc-6 but the issue still exist

Any idea please?

**Comment by ottonomy** [comment]
Hi, @OLFASALAH . It looks like you are missing dependencies for the cryptography package. This is probably libssl-dev and libffi-dev

See https://cryptography.io/en/latest/installation/ for details.
