### ISSUE TITLE
API explorer gives me the incorrect info on an API call

### ISSUE THREAD

**Issue by terrasea2** [concentricsky/badgr-server#55]
## System information: 
- Ubuntu
- Chrome 60.0.3112.101
- http://localhost:8002/docs/#!/v1/Badge_Instance_List_0

## Description of issue, including any error messages:
Not an error as such but the parameter for the POST of /v1/issuer/issuers/{issuerSlug}/badges/{badgeSlug}/assertions says there is a evidence parameter, when in fact there is not, and when I try and use it Badgr throws an exception giving  me a response of BAD REQUEST. I tracked down the problem to the use of the evidence parameter. Seems the model doesn't have that field, which is contry to the info I get from the API explorer. 

![screenshot from 2017-09-25 14-18-58](https://user-images.githubusercontent.com/25639689/30812009-aa3687e2-a201-11e7-89f4-bc954fea02b4.png)

This is a trap for the unwary

**Comment by ottonomy** [comment]
In this version of the code, the evidence url is stored in the "json" field of the model. This was fragile, so in later versions we have added an Evidence class, compatible with Open Badges 2.0 that allows many evidence urls and/or narratives to be associated with an instance. We are sorry this code is taking so long to release open source, but it should be ready soon.

**Comment by terrasea2** [comment]
No worries. It's nice to have documentation, but if it's not accurate, then sometimes it's worse than having none at all.

**Comment by ottonomy** [comment]
API documentation has been updated to be more explicit about what is expected. See https://api.badgr.io/docs Here's a screenshot of the V2 version:

<img width="1138" alt="screen shot 2018-09-21 at 1 32 44 pm" src="https://user-images.githubusercontent.com/2304883/45904770-daeb3780-bda2-11e8-91b1-424c5a2b8bfa.png">

The V1 version has been similarly updated, though the property names are slightly different. Some additional improvements to docs are something I'd love to see continue to move.
