### ISSUE TITLE
Badge is not able to link with Collection . I created a collection and then trying to add badge instance inside the collection but it's not able to link it. 

### ISSUE THREAD

**Issue by manzarul** [concentricsky/badgr-server#60]
## System information: 
- Operating system you are using:
- Browser & version:
- URL of the page where you encountered this issue:
- If your issue refers to the Badgr app in the Canvas LMS, the url of your canvas server or course where the problem occurred.
    - Course URL: 

## Description of issue, including any error messages:
api to create collections with badge:

curl -X POST \
  http://localhost:8000/v1/earner/collections \
  -H 'authorization: Token c6d0bdb8ce2425b26c2840bdca0f7b64e39be5fe' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: d4f1b5ae-ec75-a34b-6b24-9d2d64802315' \
  -d '{"name":"My badge collection","slug":"slug-10","description":"description of collections"  ,"published":false,

"badges":[
     {
	   "id":8,
	   "description":"test badge"
	   }
]}'

Response :

{
    "name": "My badge collection",
    "slug": "slug-10",
    "description": "description of collections",
    "share_hash": "",
    "share_url": "",
    "badges": []
}

Api to update badge inside collection:

curl -X PUT \
  http://localhost:8000/v1/earner/collections/slug-10 \
  -H 'authorization: Token c6d0bdb8ce2425b26c2840bdca0f7b64e39be5fe' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: d0e98330-358f-45d0-fd7d-8a2b59d9b488' \
  -d '{   
	  "name":"collection name",
	
	"badges": [
	 
	{
	 "id":8,
      "description":"description for "
     },
     {
	 "id":9,
      "description":"description for "
     }
   ]
}'

Response :

{
    "name": "collection name",
    "slug": "slug-10",
    "description": "None",
    "share_hash": "167e2ae96cc372507165b760232b9755",
    "share_url": "http://localhost:8000/earner/collections/11/167e2ae96cc372507165b760232b9755",
    "badges": []
}

if you see non of the place "badges": [] value is updated.

You can also [add a screenshot](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) or [add a file](https://github.com/blog/2061-attach-files-to-comments)

**Comment by ottonomy** [comment]
https://github.com/concentricsky/badgr-server/blob/develop/apps/backpack/tests.py#L1081 Here is code showing the method expected to update badges within collections on the current codebase version. The id is expected to be an entity_id, not an integer. If you're still having any difficulty feel free to reopen this issue with additional questions.
