### ISSUE TITLE
Can't Authorize "rw:badgeuserAdmin"

### ISSUE THREAD

**Issue by ismakutl** [concentricsky/badgr-server#72]
## System information & context:
- Operating system you are using: macOS High Sierra 10.13.4
- Browser & version: Chrome 67.0.3396.79
- URL or path of the screen where you encountered this issue or would like to see a new feature: https://api.badgr.io/docs/v2

## Description of issue or feature request, including any error messages:
So when I click on "Authorize" and chose _rw:badgeuserAdmin_ and submit, it gives an error in console (2nd image). What's the cause?
My goal is to "Get a list of access tokens for authenticated user" and it gives an error too because I'm not admin?
<img width="293" alt="badgr_error2" src="https://user-images.githubusercontent.com/22441648/41304080-6a2f07ba-6e6f-11e8-85d7-bfbb8da8f02e.png">
<img width="679" alt="badgr_error" src="https://user-images.githubusercontent.com/22441648/41304084-6c96f378-6e6f-11e8-8073-cf0986c3f126.png">

**Comment by ismakutl** [comment]
randomly works, didn't change anything

**Comment by ottonomy** [comment]
We will be resolving this for a near-term release. For now, to get an auth token working on the docs page, do not select this scope when requesting a token.
