### ISSUE TITLE
How can we stop users from creating new Issuers?

### ISSUE THREAD

**Issue by AshwinJd** [concentricsky/badgr-server#75]
I have set BADGR_APPROVED_ISSUERS_ONLY to true, still the new users who creates an account is able to create new Issuers, how can I block the new users who logs in from creating Issuers?

**Comment by ottonomy** [comment]
@AshwinJd That appears to be a bug. We don't use that feature in our deployed environments, and it looks like there is not an appropriate unit test. We are working on improved features around this capability at the moment, and an update is likely expected within a month or so, but pull requests specifically for fixing the bug with the existing capability are welcome.

**Comment by 6tine** [comment]
Hi! Have you fix the bug or not yet ? :)

**Comment by 6tine** [comment]
Hi ! Have you fixed this feature ?

**Comment by batcaverna** [comment]
Greetings @ottonomy,

Can you please check this solution? It's a band-aid and depends on creating at least one issuer manually in the /staff area, but it kind of works:

1 - add:   **features: { disableIssuers: true,},** in environment.ts
2 - use this patch:

```
--- app.component.ts.bak        2019-11-14 16:59:05.015033914 -0300
+++ src/app/app.component.ts    2019-11-14 18:06:59.273971537 -0300
@@ -166,9 +166,10 @@
        }
 
        showIssuersTab = false;
-       shouldShowIssuersTab = () => this.showIssuersTab = !this.features.disableIssuers || (this.issuers && this.issuers.length > 0);
-
-       toggleMobileNav() {
+       shouldShowIssuersTab = function() { 
+           this.showIssuersTab = (this.features.disableIssuers && (this.issuers && this.issuers.length > 0));
+       }
+        toggleMobileNav() {
                this.mobileNavOpen = !this.mobileNavOpen;
        }
        get isOAuthAuthorizationInProcess() {

```

TIA,
JCF

**Comment by ottonomy** [comment]
@batcaverna thanks for the UI side comment. Yes, the "theme" can be configured to hide the issuers tab for users who don't have it, but now @AshwinJd and @6tine I have committed a fix in 2e734b to the issue on the API side as well. Even if you don't disable the relevant create button on the UI side, this will now be disabled for your users except when added to a group with the relevant permission when this setting is configured. Some further work likely could be done to pass user-specific permissions information to the UI to enable the create issuer button only for SOME users who happen to have the relevant permission.

**Comment by matty111** [comment]
The same of #254
