### ISSUE TITLE
Endless redirect loop in JSONComponentView

### ISSUE THREAD

**Issue by smoquet** [concentricsky/badgr-server#85]
if self.is_requesting_html():
            return HttpResponseRedirect(redirect_to=self.get_badgrapp_redirect())

redirects to itself and loops endlessly, found this by clicking on the 'view' button in the badge recipient list in the UI.

**Comment by ottonomy** [comment]
6873e4a5f4ee34cc7477982602c765489e537779 clarifies that the BadgrApp should be configured to describe the installed location of a badgr-ui server. The CORS (and public pages redirect) properties should not point at the badgr-server install location, or it will result in this loop as described. Thanks!
