### ISSUE TITLE
email on earned badge has "Oregon Badge Alliance" header image

### ISSUE THREAD

**Issue by sleslie** [concentricsky/badgr-server#9]
obviously just an artefact from an initial deployment, but the resulting email to someone who has earned a badge has a large image of "Oregon Badge Alliance" plus probably want to alter text above "learn more" button to be less specific to that project too.

**Comment by ottonomy** [comment]
Thanks. I'll have this one fixed by the end of the night.

**Comment by ottonomy** [comment]
Fixed in development, release scheduled for tomorrow.
